export const JFDI_ADD_NEW = 'JFDI_ADD_NEW';
export const JFDI_EDIT_CARD = 'JFDI_EDIT_CARD';
export const JFDI_RECEIVE_APP_STATE = 'JFDI_RECEIVE_APP_STATE';
export const JFDI_REQUEST_APP_STATE = 'JFDI_REQUEST_APP_STATE';
export const JFDI_SAVE_GOAL = 'JFDI_SAVE_GOAL';
export const JFDI_UPDATE_BUCKET = 'JFDI_UPDATE_BUCKET';
export const JFDI_UPDATE_DESCRIPTION = 'JFDI_UPDATE_DESCRIPTION';
